language: ruby
dist: trusty

rvm:
  - 2.6

before_install:
  - travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler -v 1.17.3
  - travis_retry gem uninstall -i /home/travis/.rvm/gems/ruby-2.3.7@global bundler || echo

script:
  - bundle exec rake spec

sudo: false
cache: bundler
notifications:
  slack:
    secure: OhClKo2Gn26gevN773CRR2NAHzmkrzGrVTHsAKm4dgNFqnaBVZGNv2kzjAFsy0CEjZJw3433NtaJdrWpLozdHFA5g7fhOTqB2y7Oh+8PsoS4qWsosKcjtCYt7BmNbEFkGaHKAdQjO/vGFml7tAOk/DtVRnfX6QgVUBjky2ao7XM=


