language: ruby
dist: focal

rvm:
  - 2.6
  - 2.7
  - 3.0

before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler

script:
  - bundle exec rake spec

sudo: false
cache: bundler
notifications:
  slack:
    secure: OhClKo2Gn26gevN773CRR2NAHzmkrzGrVTHsAKm4dgNFqnaBVZGNv2kzjAFsy0CEjZJw3433NtaJdrWpLozdHFA5g7fhOTqB2y7Oh+8PsoS4qWsosKcjtCYt7BmNbEFkGaHKAdQjO/vGFml7tAOk/DtVRnfX6QgVUBjky2ao7XM=
